# Series

In [3]:
import pandas as pd

series_test = pd.Series([100, 200, 300])

series_test

0    100
1    200
2    300
dtype: int64

In [9]:
series_test2 = pd.Series({1999: 48,
                          2000: 65,
                          2001: 89})

series_test2

1999    48
2000    65
2001    89
dtype: int64

# DataFrame

In [10]:
frame_test = pd.DataFrame({1999: [74, 38, 39],
                           2000: [10, 84, 13],
                           2001: [58, 97, 164]})
frame_test

   1999  2000  2001
0    74    10    58
1    38    84    97
2    39    13   164

In [12]:
frame_test2 = pd.DataFrame([[74, 38, 39],
                           [10, 84, 13],
                           [58, 97, 164]])

frame_test2

    0   1    2
0  74  38   39
1  10  84   13
2  58  97  164

# Read data

In [12]:
pd.options.display.max_rows = 10

semana = pd.read_csv('../web_scrapper/semana_2019_11_06_articles.csv')

type(semana)

semana

,body,title,url
0,Este martes en la noche se cumpli el sorteo de...,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//deportes/articulo/asi-...
1,"""Con este nivel de juego es difcil que nos d p...",Por qu James pasa por su peor momento desde su...,https://www.semana.com//deportes/articulo/cham...
2,Un experimento con resultados no esperados. As...,Sony yMicrosoftse unen para desarrollar videoj...,https://www.semana.com//vida-moderna/articulo/...
3,"Durante el programa Vicky en Semana, de la per...",As estn las cuentas en el Congreso para sacar ...,https://www.semana.com//nacion/articulo/roy-ba...
4,Poco a poco se conocen detalles de la estremec...,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//mundo/articulo/el-acto...
...,...,...,...
39,La iluminacin de calles o la recoleccin de bas...,Educacin y Premios Nobel 2019,https://www.dinero.com/pais/articulo/como-se-i...
40,El nombre de Margarita Rosa de Francisco est g...,Escribo para no ignorarme para tenerme ms en c...,https://www.semana.com//gente/articulo/margari...
41,En el Congreso volvi a aterrizar una iniciativ...,Llmelo como quiera: Corte Constitucional acaba...,https://www.semana.com//nacion/articulo/radica...
42,"Ayer en la maana, en los pasillos del Congreso...","""Bombardeo contra campamento de Gildardo Cucho...",https://www.semana.com//nacion/articulo/mocion...
43,James Rodrguez est viviendo momentos difciles ...,"""No es de Shannon"": las revelaciones sobre el ...",https://www.semana.com//deportes/articulo/por-...

# Index and selection

In [13]:
# dictionary like

semana['title']

0     La nueva pelcula de 'Terminator', un fracaso d...
1     Por qu James pasa por su peor momento desde su...
2     Sony yMicrosoftse unen para desarrollar videoj...
3     As estn las cuentas en el Congreso para sacar ...
4     La nueva pelcula de 'Terminator', un fracaso d...
                            ...
39                        Educacin y Premios Nobel 2019
40    Escribo para no ignorarme para tenerme ms en c...
41    Llmelo como quiera: Corte Constitucional acaba...
42    "Bombardeo contra campamento de Gildardo Cucho...
43    "No es de Shannon": las revelaciones sobre el ...
Name: title, Length: 44, dtype: object

In [14]:
semana[['title', 'url']]

,title,url
0,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//deportes/articulo/asi-...
1,Por qu James pasa por su peor momento desde su...,https://www.semana.com//deportes/articulo/cham...
2,Sony yMicrosoftse unen para desarrollar videoj...,https://www.semana.com//vida-moderna/articulo/...
3,As estn las cuentas en el Congreso para sacar ...,https://www.semana.com//nacion/articulo/roy-ba...
4,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//mundo/articulo/el-acto...
...,...,...
39,Educacin y Premios Nobel 2019,https://www.dinero.com/pais/articulo/como-se-i...
40,Escribo para no ignorarme para tenerme ms en c...,https://www.semana.com//gente/articulo/margari...
41,Llmelo como quiera: Corte Constitucional acaba...,https://www.semana.com//nacion/articulo/radica...
42,"""Bombardeo contra campamento de Gildardo Cucho...",https://www.semana.com//nacion/articulo/mocion...
43,"""No es de Shannon"": las revelaciones sobre el ...",https://www.semana.com//deportes/articulo/por-...

In [15]:
# Numpy like

semana.iloc[10:15]

,body,title,url
10,Cuando era una niala cineasta chilena Lissette...,Este es un Gobierno cmplice de la dictadura: M...,https://www.semana.com//mundo/articulo/lissett...
11,Durante el debate de control poltico que se ll...,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//nacion/articulo/dario-...
12,Mientras el presidente Ivn Duque sala de un ev...,La cadena de errores que termin con la renunci...,https://www.semana.com//nacion/articulo/de-que...
13,"""Declaramos de forma clara e inequvoca que el ...","La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//vida-moderna/articulo/...
14,Tres turistas mexicanos y una suiza resultaron...,Un siglo de consecuencias en Oriente Medio,https://www.semana.com//mundo/articulo/conmoci...

In [16]:
semana.iloc[12]['title']

'La cadena de errores que termin con la renuncia del ministro Botero'

In [18]:
semana.iloc[:5, 0]

0    Este martes en la noche se cumpli el sorteo de...
1    "Con este nivel de juego es difcil que nos d p...
2    Un experimento con resultados no esperados. As...
3    Durante el programa Vicky en Semana, de la per...
4    Poco a poco se conocen detalles de la estremec...
Name: body, dtype: object

In [20]:
semana.loc[:, 'body': 'title']

,body,title
0,Este martes en la noche se cumpli el sorteo de...,"La nueva pelcula de 'Terminator', un fracaso d..."
1,"""Con este nivel de juego es difcil que nos d p...",Por qu James pasa por su peor momento desde su...
2,Un experimento con resultados no esperados. As...,Sony yMicrosoftse unen para desarrollar videoj...
3,"Durante el programa Vicky en Semana, de la per...",As estn las cuentas en el Congreso para sacar ...
4,Poco a poco se conocen detalles de la estremec...,"La nueva pelcula de 'Terminator', un fracaso d..."
...,...,...
39,La iluminacin de calles o la recoleccin de bas...,Educacin y Premios Nobel 2019
40,El nombre de Margarita Rosa de Francisco est g...,Escribo para no ignorarme para tenerme ms en c...
41,En el Congreso volvi a aterrizar una iniciativ...,Llmelo como quiera: Corte Constitucional acaba...
42,"Ayer en la maana, en los pasillos del Congreso...","""Bombardeo contra campamento de Gildardo Cucho..."
43,James Rodrguez est viviendo momentos difciles ...,"""No es de Shannon"": las revelaciones sobre el ..."

# Data wrangling

In [22]:
# 1. aÃ±adir newspaper_uid al DataFrame

semana['newspaper_uid'] = 'semana'

semana

,body,title,url,newspaper_uid
0,Este martes en la noche se cumpli el sorteo de...,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//deportes/articulo/asi-...,semana
1,"""Con este nivel de juego es difcil que nos d p...",Por qu James pasa por su peor momento desde su...,https://www.semana.com//deportes/articulo/cham...,semana
2,Un experimento con resultados no esperados. As...,Sony yMicrosoftse unen para desarrollar videoj...,https://www.semana.com//vida-moderna/articulo/...,semana
3,"Durante el programa Vicky en Semana, de la per...",As estn las cuentas en el Congreso para sacar ...,https://www.semana.com//nacion/articulo/roy-ba...,semana
4,Poco a poco se conocen detalles de la estremec...,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//mundo/articulo/el-acto...,semana
...,...,...,...,...
39,La iluminacin de calles o la recoleccin de bas...,Educacin y Premios Nobel 2019,https://www.dinero.com/pais/articulo/como-se-i...,semana
40,El nombre de Margarita Rosa de Francisco est g...,Escribo para no ignorarme para tenerme ms en c...,https://www.semana.com//gente/articulo/margari...,semana
41,En el Congreso volvi a aterrizar una iniciativ...,Llmelo como quiera: Corte Constitucional acaba...,https://www.semana.com//nacion/articulo/radica...,semana
42,"Ayer en la maana, en los pasillos del Congreso...","""Bombardeo contra campamento de Gildardo Cucho...",https://www.semana.com//nacion/articulo/mocion...,semana
43,James Rodrguez est viviendo momentos difciles ...,"""No es de Shannon"": las revelaciones sobre el ...",https://www.semana.com//deportes/articulo/por-...,semana

In [25]:
# 2. obtener el host

from urllib.parse import urlparse

semana['host'] = semana['url'].apply(lambda url: urlparse(url).netloc)

semana

,body,title,url,newspaper_uid,host
0,Este martes en la noche se cumpli el sorteo de...,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//deportes/articulo/asi-...,semana,www.semana.com
1,"""Con este nivel de juego es difcil que nos d p...",Por qu James pasa por su peor momento desde su...,https://www.semana.com//deportes/articulo/cham...,semana,www.semana.com
2,Un experimento con resultados no esperados. As...,Sony yMicrosoftse unen para desarrollar videoj...,https://www.semana.com//vida-moderna/articulo/...,semana,www.semana.com
3,"Durante el programa Vicky en Semana, de la per...",As estn las cuentas en el Congreso para sacar ...,https://www.semana.com//nacion/articulo/roy-ba...,semana,www.semana.com
4,Poco a poco se conocen detalles de la estremec...,"La nueva pelcula de 'Terminator', un fracaso d...",https://www.semana.com//mundo/articulo/el-acto...,semana,www.semana.com
...,...,...,...,...,...
39,La iluminacin de calles o la recoleccin de bas...,Educacin y Premios Nobel 2019,https://www.dinero.com/pais/articulo/como-se-i...,semana,www.dinero.com
40,El nombre de Margarita Rosa de Francisco est g...,Escribo para no ignorarme para tenerme ms en c...,https://www.semana.com//gente/articulo/margari...,semana,www.semana.com
41,En el Congreso volvi a aterrizar una iniciativ...,Llmelo como quiera: Corte Constitucional acaba...,https://www.semana.com//nacion/articulo/radica...,semana,www.semana.com
42,"Ayer en la maana, en los pasillos del Congreso...","""Bombardeo contra campamento de Gildardo Cucho...",https://www.semana.com//nacion/articulo/mocion...,semana,www.semana.com
43,James Rodrguez est viviendo momentos difciles ...,"""No es de Shannon"": las revelaciones sobre el ...",https://www.semana.com//deportes/articulo/por-...,semana,www.semana.com

In [26]:
semana['host'].value_counts()

www.semana.com            36
www.revistaarcadia.com     5
www.dinero.com             3
Name: host, dtype: int64